shared:
  terminals: &terminals
    - kitty
    - emacs
    - vim
    - code
    - code-url-handler
  hhkb: &hhkb
    - PFU Limited HHKB-Hybrid
    - HHKB-Hybrid_1 Keyboard
    - HHKB-Hybrid_2 Keyboard
    - HHKB-Hybrid_3 Keyboard
    - HHKB-Hybrid_4 Keyboard

modmap:
  - device:
      only: *hhkb
    remap:
      Super_L: Ctrl_L
      Alt_L: Super_L
      grave: Alt_L
  - device:
      only: *hhkb
    application:
      not: *terminals
    remap:
      Ctrl_L: CapsLock

virtual_modifiers:
  - CapsLock

keymap:
  - name: Emacs
    application:
      not: *terminals
    remap:
      CapsLock-n: { with_mark: down }
      CapsLock-p: { with_mark: up }
      CapsLock-f: { with_mark: right }
      CapsLock-b: { with_mark: left }
      CapsLock-a: { with_mark: home }
      CapsLock-e: { with_mark: end }
      M-b: { with_mark: Ctrl-left }
      M-f: { with_mark: Ctrl-right }
      M-v: { with_mark: pageup }
      CapsLock-v: { with_mark: pagedown }
      M-Shift-comma: { with_mark: Ctrl-home }
      M-Shift-dot: { with_mark: Ctrl-end }
      CapsLock-d: [delete, { set_mark: false }]
      CapsLock-h: [backspace, { set_mark: false }]
      M-backspace: [Ctrl-backspace, { set_mark: false }]
      CapsLock-M-space: [Ctrl-Shift-right, { set_mark: true }]
      CapsLock-k: [Shift-end, Ctrl-x, { set_mark: false }]
      CapsLock-w: [Ctrl-x, { set_mark: false }]
      M-w: [Ctrl-c, { set_mark: false }]
      CapsLock-y: [Ctrl-v, { set_mark: false }]
      CapsLock-j: enter
      CapsLock-m: enter
      CapsLock-o: [enter, left]
      CapsLock-slash: [Ctrl-z, { set_mark: false }]
      CapsLock-space: { set_mark: true }
      CapsLock-g: [esc, { set_mark: false }]
      CapsLock-space: { set_mark: true }
      CapsLock-s: Ctrl-f
      CapsLock-r: Shift-F3
      CapsLock-x:
        remap:
          b: [{ set_mark: false }, Ctrl-n]
          h: [Ctrl-home, Ctrl-a, { set_mark: true }]
          CapsLock-f: Ctrl-o
          CapsLock-s: Ctrl-s
          k: Ctrl-f4
          C-c: Ctrl-q
          u: [Ctrl-z, { set_mark: false }]
  - name: underscore
    remap:
      ro: Shift-ro
